default: &default
  fetch_vice:
    class: FetchViceJob
    cron: '59 23 * * 0'
    args: 1
  fetch_elle:
    class: FetchElleJob
    cron: '59 22 * * 0'
  fetch_allure:
    class: FetchAllureJob
    cron: '59 21 * * 1'
  fetch_auto:
    class: FetchAutoJob
    cron: '59 20 * * 1'
  fetch_cosmo:
    class: FetchCosmoJob
    cron: '59 19 * * 1'
    args: 1
  fetch_mask:
    class: FetchMaskJob
    cron: '59 18 * * 1'
  fetch_cut:
    class: FetchCutJob
    cron: '59 17 * * 1'
    args: 50
  fetch_teen_vogue:
    class: FetchTeenVogueJob
    cron: '59 16 * * 1'
    args: 1

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
